### ISSUE TITLE
[Tracking] LEVM EF tests

### ISSUE THREAD

**Issue by ilitteri** [lambdaclass/ethrex#1204]
[Link to list](https://github.com/lambdaclass/lambda_ethereum_rust/issues?q=is%3Aopen+is%3Aissue+label%3Alevm+label%3Aef-tests).
- [x] https://github.com/lambdaclass/lambda_ethereum_rust/issues/742
- [x] https://github.com/lambdaclass/lambda_ethereum_rust/issues/743
- [x] https://github.com/lambdaclass/lambda_ethereum_rust/issues/744
- [x] https://github.com/lambdaclass/lambda_ethereum_rust/issues/745
- [x] https://github.com/lambdaclass/lambda_ethereum_rust/issues/746
- [x] https://github.com/lambdaclass/lambda_ethereum_rust/issues/747
- [x] https://github.com/lambdaclass/lambda_ethereum_rust/issues/748
- [x] https://github.com/lambdaclass/lambda_ethereum_rust/issues/749
- [x] https://github.com/lambdaclass/lambda_ethereum_rust/issues/750
- [x] https://github.com/lambdaclass/lambda_ethereum_rust/issues/751
- [x] https://github.com/lambdaclass/lambda_ethereum_rust/issues/752
- [x] https://github.com/lambdaclass/lambda_ethereum_rust/issues/753
- [x] https://github.com/lambdaclass/lambda_ethereum_rust/issues/754
- [x] https://github.com/lambdaclass/lambda_ethereum_rust/issues/755
- [x] https://github.com/lambdaclass/lambda_ethereum_rust/issues/756
- [x] https://github.com/lambdaclass/lambda_ethereum_rust/issues/757
- [x] https://github.com/lambdaclass/lambda_ethereum_rust/issues/758
- [x] https://github.com/lambdaclass/lambda_ethereum_rust/issues/759
- [x] https://github.com/lambdaclass/lambda_ethereum_rust/issues/760
- [x] https://github.com/lambdaclass/lambda_ethereum_rust/issues/761
- [x] https://github.com/lambdaclass/lambda_ethereum_rust/issues/762
- [x] https://github.com/lambdaclass/lambda_ethereum_rust/issues/763
- [x] https://github.com/lambdaclass/lambda_ethereum_rust/issues/764
- [x] https://github.com/lambdaclass/lambda_ethereum_rust/issues/765
- [x] https://github.com/lambdaclass/lambda_ethereum_rust/issues/766
- [x] https://github.com/lambdaclass/lambda_ethereum_rust/issues/767
- [x] https://github.com/lambdaclass/lambda_ethereum_rust/issues/768
- [x] https://github.com/lambdaclass/lambda_ethereum_rust/issues/769
- [x] https://github.com/lambdaclass/lambda_ethereum_rust/issues/770
- [x] https://github.com/lambdaclass/lambda_ethereum_rust/issues/771
- [x] https://github.com/lambdaclass/lambda_ethereum_rust/issues/772
- [x] https://github.com/lambdaclass/lambda_ethereum_rust/issues/773
- [x] https://github.com/lambdaclass/lambda_ethereum_rust/issues/774
- [x] https://github.com/lambdaclass/lambda_ethereum_rust/issues/775
- [x] https://github.com/lambdaclass/lambda_ethereum_rust/issues/776
- [x] https://github.com/lambdaclass/lambda_ethereum_rust/issues/777
- [x] https://github.com/lambdaclass/lambda_ethereum_rust/issues/778
- [x] https://github.com/lambdaclass/lambda_ethereum_rust/issues/779
- [x] https://github.com/lambdaclass/lambda_ethereum_rust/issues/780
- [x] https://github.com/lambdaclass/lambda_ethereum_rust/issues/781
- [x] https://github.com/lambdaclass/lambda_ethereum_rust/issues/782
- [x] https://github.com/lambdaclass/lambda_ethereum_rust/issues/783
- [x] https://github.com/lambdaclass/lambda_ethereum_rust/issues/784
- [x] https://github.com/lambdaclass/lambda_ethereum_rust/issues/785
- [x] https://github.com/lambdaclass/lambda_ethereum_rust/issues/786
