### ISSUE TITLE
[Tracking] Hive `engine-cancun` test suite

### ISSUE THREAD

**Issue by mpaulucci** [lambdaclass/ethrex#1285]
These are the failing tests

```
make run-hive SIMULATION=ethereum/engine TEST_PATTERN="engine-cancun" > results.txt
cat results.txt | awk '/pass=true/{getline; print}' | sed -n 's/.*"\(.*\)".*/\1/p'
```

- [] Blob Transactions On Block 1, Cancun Genesis (Cancun) (ethrex)
- [] Blob Transaction Ordering, Single Account, Single Blob (Cancun) (ethrex)
- [] Blob Transaction Ordering, Single Account, Dual Blob (Cancun) (ethrex)
- [] Blob Transaction Ordering, Multiple Accounts (Cancun) (ethrex)
- [] Blob Transaction Ordering, Multiple Clients (Cancun) (ethrex)
- [] Parallel Blob Transactions (Cancun) (ethrex)
- [] ForkchoiceUpdatedV3 Set Head to Shanghai Payload, Null Payload Attributes (Cancun) (ethrex)
- [] GetPayloadV3 To Request Shanghai Payload (Cancun) (ethrex)
- [] NewPayloadV3 After Cancun, 0x00 ExcessBlobGas, Nil BlobGasUsed, Empty Array Versioned Hashes (Cancun) (ethrex)
- [] NewPayloadV3 After Cancun, 0x00 Blob Fields, Empty Array Versioned Hashes, Nil Beacon Root (Cancun) (ethrex)
- [] ForkchoiceUpdatedV2 then ForkchoiceUpdatedV3 Valid Payload Building Requests (Cancun) (ethrex)
- [] NewPayloadV3 Versioned Hashes, Extra Hash, Syncing=False (Cancun) (ethrex)
- [] NewPayloadV3 Versioned Hashes, Out of Order, Syncing=False (Cancun) (ethrex)
- [] NewPayloadV3 Versioned Hashes, Repeated Hash, Syncing=False (Cancun) (ethrex)
- [] NewPayloadV3 Versioned Hashes, Incorrect Hash, Syncing=False (Cancun) (ethrex)
- [] NewPayloadV3 Versioned Hashes, Incorrect Version, Syncing=False (Cancun) (ethrex)
- [] NewPayloadV3 Versioned Hashes, Nil Hashes, Syncing=False (Cancun) (ethrex)
- [] NewPayloadV3 Versioned Hashes, Empty Hashes, Syncing=False (Cancun) (ethrex)
- [] NewPayloadV3 Versioned Hashes, Non-Empty Hashes, Syncing=False (Cancun) (ethrex)
- [] NewPayloadV3 Versioned Hashes, Missing Hash, Syncing=True (Cancun) (ethrex)
- [] NewPayloadV3 Versioned Hashes, Extra Hash, Syncing=True (Cancun) (ethrex)
- [] NewPayloadV3 Versioned Hashes, Out of Order, Syncing=True (Cancun) (ethrex)
- [] NewPayloadV3 Versioned Hashes, Repeated Hash, Syncing=True (Cancun) (ethrex)
- [] NewPayloadV3 Versioned Hashes, Incorrect Hash, Syncing=True (Cancun) (ethrex)
- [] NewPayloadV3 Versioned Hashes, Incorrect Version, Syncing=True (Cancun) (ethrex)
- [] NewPayloadV3 Versioned Hashes, Nil Hashes, Syncing=True (Cancun) (ethrex)
- [] NewPayloadV3 Versioned Hashes, Empty Hashes, Syncing=True (Cancun) (ethrex)
- [] NewPayloadV3 Versioned Hashes, Non-Empty Hashes, Syncing=True (Cancun) (ethrex)
- [] Incorrect BlobGasUsed, Non-Zero on Zero Blobs (Cancun) (ethrex)
- [] Incorrect BlobGasUsed, GAS_PER_BLOB on Zero Blobs (Cancun) (ethrex)
- [] Request Blob Pooled Transactions Single (Cancun) (ethrex)
- [] Bad Hash on NewPayload (Syncing=false, Sidechain=true) (Cancun) (ethrex)
- [] Bad Hash on NewPayload (Syncing=true, Sidechain=false) (Cancun) (ethrex)
- [] Bad Hash on NewPayload (Syncing=true, Sidechain=true) (Cancun) (ethrex)
- [] ParentHash equals BlockHash on NewPayload, Syncing=False (Cancun) (ethrex)
- [] ParentHash equals BlockHash on NewPayload, Syncing=True (Cancun) (ethrex)
- [] RPC: Latest Block on NewPayload (Cancun) (ethrex)
- [] RPC: Latest Block on HeadBlockHash Update (Cancun) (ethrex)
- [] RPC: Safe Block on SafeBlockHash Update (Cancun) (ethrex)
- [] RPC: Finalized Block on FinalizedBlockHash Update (Cancun) (ethrex)
- [] Inconsistent Head in ForkchoiceState (Cancun) (ethrex)
- [] Unknown HeadBlockHash (Cancun) (ethrex)
- [] Inconsistent Safe in ForkchoiceState (Cancun) (ethrex)
- [] Unknown SafeBlockHash (Cancun) (ethrex)
- [] Inconsistent Finalized in ForkchoiceState (Cancun) (ethrex)
- [] Unknown FinalizedBlockHash (Cancun) (ethrex)
- [] Invalid PayloadAttributes, Zero timestamp, Syncing=False (Cancun) (ethrex)
- [] Invalid PayloadAttributes, Zero timestamp, Syncing=True (Cancun) (ethrex)
- [] Invalid PayloadAttributes, Parent timestamp, Syncing=False (Cancun) (ethrex)
- [] Invalid PayloadAttributes, Parent timestamp, Syncing=True (Cancun) (ethrex)
- [] Unique Payload ID, Increase Timestamp (Cancun) (ethrex)
- [] Unique Payload ID, Modify Random (Cancun) (ethrex)
- [] Unique Payload ID, Modify SuggestedFeeRecipient (Cancun) (ethrex)
- [] ForkchoiceUpdated Version on Payload Request: Early upgrade (Cancun) (ethrex)
- [] Re-Execute Payload (Cancun) (ethrex)
- [] In-Order Consecutive Payload Execution (Cancun) (ethrex)
- [] Multiple New Payloads Extending Canonical Chain, Set Head to First Payload Received (Cancun) (ethrex)
- [] Multiple New Payloads Extending Canonical Chain, Wait for Canonical Payload (Cancun) (ethrex)
- [] Valid NewPayload->ForkchoiceUpdated on Syncing Client (Cancun) (ethrex)
- [] NewPayload with Missing ForkchoiceUpdated (Cancun) (ethrex)
- [] Invalid NewPayload, ParentHash, Syncing=False, EmptyTxs=False, DynFeeTxs=False (Cancun) (ethrex)
- [] Invalid NewPayload, ParentHash, Syncing=True, EmptyTxs=False, DynFeeTxs=False (Cancun) (ethrex)
- [] Invalid NewPayload, StateRoot, Syncing=False, EmptyTxs=True, DynFeeTxs=False (Cancun) (ethrex)
- [] Invalid NewPayload, StateRoot, Syncing=False, EmptyTxs=False, DynFeeTxs=False (Cancun) (ethrex)
- [] Invalid NewPayload, StateRoot, Syncing=True, EmptyTxs=True, DynFeeTxs=False (Cancun) (ethrex)
- [] Invalid NewPayload, StateRoot, Syncing=True, EmptyTxs=False, DynFeeTxs=False (Cancun) (ethrex)
- [] Invalid NewPayload, ReceiptsRoot, Syncing=False, EmptyTxs=False, DynFeeTxs=False (Cancun) (ethrex)
- [] Invalid NewPayload, Number, Syncing=True, EmptyTxs=False, DynFeeTxs=False (Cancun) (ethrex)
- [] Invalid NewPayload, GasLimit, Syncing=False, EmptyTxs=False, DynFeeTxs=False (Cancun) (ethrex)
- [] Invalid NewPayload, GasLimit, Syncing=True, EmptyTxs=False, DynFeeTxs=False (Cancun) (ethrex)
- [] Invalid NewPayload, GasUsed, Syncing=False, EmptyTxs=False, DynFeeTxs=False (Cancun) (ethrex)
- [] Invalid NewPayload, GasUsed, Syncing=True, EmptyTxs=False, DynFeeTxs=False (Cancun) (ethrex)
- [] Invalid NewPayload, Timestamp, Syncing=False, EmptyTxs=False, DynFeeTxs=False (Cancun) (ethrex)
- [] Invalid NewPayload, Timestamp, Syncing=True, EmptyTxs=False, DynFeeTxs=False (Cancun) (ethrex)
- [] Invalid NewPayload, PrevRandao, Syncing=False, EmptyTxs=False, DynFeeTxs=False (Cancun) (ethrex)
- [] Invalid NewPayload, PrevRandao, Syncing=True, EmptyTxs=False, DynFeeTxs=False (Cancun) (ethrex)
- [] Invalid NewPayload, Incomplete Transactions, Syncing=False, EmptyTxs=False, DynFeeTxs=False (Cancun) (ethrex)
- [] Invalid NewPayload, Incomplete Transactions, Syncing=True, EmptyTxs=False, DynFeeTxs=False (Cancun) (ethrex)
- [] Payload Build after New Invalid Payload: Invalid StateRoot (Cancun) (ethrex)
- [] Invalid NewPayload, Transaction Signature, Syncing=False, EmptyTxs=False, DynFeeTxs=False (Cancun) (ethrex)
- [] Invalid NewPayload, Transaction Signature, Syncing=False, EmptyTxs=False, DynFeeTxs=True (Cancun) (ethrex)
- [] Invalid NewPayload, Transaction Signature, Syncing=True, EmptyTxs=False, DynFeeTxs=False (Cancun) (ethrex)
- [] Invalid NewPayload, Transaction Signature, Syncing=True, EmptyTxs=False, DynFeeTxs=True (Cancun) (ethrex)
- [] Invalid NewPayload, Transaction Nonce, Syncing=False, EmptyTxs=False, DynFeeTxs=False (Cancun) (ethrex)
- [] Invalid NewPayload, Transaction Nonce, Syncing=False, EmptyTxs=False, DynFeeTxs=True (Cancun) (ethrex)
- [] Invalid NewPayload, Transaction Nonce, Syncing=True, EmptyTxs=False, DynFeeTxs=False (Cancun) (ethrex)
- [] Invalid NewPayload, Transaction Nonce, Syncing=True, EmptyTxs=False, DynFeeTxs=True (Cancun) (ethrex)
- [] Invalid NewPayload, Transaction GasPrice, Syncing=False, EmptyTxs=False, DynFeeTxs=False (Cancun) (ethrex)
- [] Invalid NewPayload, Transaction GasPrice, Syncing=False, EmptyTxs=False, DynFeeTxs=True (Cancun) (ethrex)
- [] Invalid NewPayload, Transaction GasPrice, Syncing=True, EmptyTxs=False, DynFeeTxs=False (Cancun) (ethrex)
- [] Invalid NewPayload, Transaction GasPrice, Syncing=True, EmptyTxs=False, DynFeeTxs=True (Cancun) (ethrex)
- [] Invalid NewPayload, Transaction GasTipCapPrice, Syncing=False, EmptyTxs=False, DynFeeTxs=True (Cancun) (ethrex)
- [] Invalid NewPayload, Transaction GasTipCapPrice, Syncing=True, EmptyTxs=False, DynFeeTxs=True (Cancun) (ethrex)
- [] Invalid NewPayload, Transaction Gas, Syncing=False, EmptyTxs=False, DynFeeTxs=False (Cancun) (ethrex)
- [] Invalid NewPayload, Transaction Gas, Syncing=False, EmptyTxs=False, DynFeeTxs=True (Cancun) (ethrex)
- [] Invalid NewPayload, Transaction Gas, Syncing=True, EmptyTxs=False, DynFeeTxs=False (Cancun) (ethrex)
- [] Invalid NewPayload, Transaction Gas, Syncing=True, EmptyTxs=False, DynFeeTxs=True (Cancun) (ethrex)
- [] Invalid NewPayload, Transaction Value, Syncing=False, EmptyTxs=False, DynFeeTxs=False (Cancun) (ethrex)
- [] Invalid NewPayload, Transaction Value, Syncing=False, EmptyTxs=False, DynFeeTxs=True (Cancun) (ethrex)
- [] Invalid NewPayload, Transaction Value, Syncing=True, EmptyTxs=False, DynFeeTxs=False (Cancun) (ethrex)
- [] Invalid NewPayload, Transaction Value, Syncing=True, EmptyTxs=False, DynFeeTxs=True (Cancun) (ethrex)
- [] Invalid NewPayload, Transaction ChainID, Syncing=False, EmptyTxs=False, DynFeeTxs=False (Cancun) (ethrex)
- [] Invalid NewPayload, Transaction ChainID, Syncing=False, EmptyTxs=False, DynFeeTxs=True (Cancun) (ethrex)
- [] Invalid NewPayload, Transaction ChainID, Syncing=True, EmptyTxs=False, DynFeeTxs=False (Cancun) (ethrex)
- [] Invalid NewPayload, Transaction ChainID, Syncing=True, EmptyTxs=False, DynFeeTxs=True (Cancun) (ethrex)
- [] Build Payload with Invalid ChainID Transaction, LegacyTransactions (Cancun) (ethrex)
- [] Build Payload with Invalid ChainID Transaction, DynamicFeeTransactions (Cancun) (ethrex)
- [] Invalid Missing Ancestor ReOrg, StateRoot, EmptyTxs=False, Invalid P1 (Cancun) (ethrex)
- [] Invalid Missing Ancestor ReOrg, StateRoot, EmptyTxs=True, Invalid P1 (Cancun) (ethrex)
- [] Invalid Missing Ancestor ReOrg, StateRoot, EmptyTxs=False, Invalid P9 (Cancun) (ethrex)
- [] Invalid Missing Ancestor ReOrg, StateRoot, EmptyTxs=True, Invalid P9 (Cancun) (ethrex)
- [] Invalid Missing Ancestor ReOrg, StateRoot, EmptyTxs=False, Invalid P10 (Cancun) (ethrex)
- [] Invalid Missing Ancestor ReOrg, StateRoot, EmptyTxs=True, Invalid P10 (Cancun) (ethrex)
- [] Invalid Missing Ancestor Syncing ReOrg, StateRoot, EmptyTxs=True, CanonicalReOrg=False, Invalid P9 (Cancun) (ethrex)
- [] Re-org to Previously Validated Sidechain Payload (Cancun) (ethrex)
- [] Safe Re-Org to Side Chain (Cancun) (ethrex)
- [] Transaction Re-Org, Re-Org Out (Cancun) (ethrex)
- [] Re-Org Back into Canonical Chain, Depth=5 (Cancun) (ethrex)
- [] Re-Org Back into Canonical Chain, Depth=10, Execute Side Payload on Re-Org (Cancun) (ethrex)
- [] Suggested Fee Recipient Test, DynamicFeeTransactions (Cancun) (ethrex)
- [] PrevRandao Opcode Transactions Test, LegacyTransactions (Cancun) (ethrex)
- [] PrevRandao Opcode Transactions Test, DynamicFeeTransactions (Cancun) (ethrex)
- [] Fork ID: Genesis=0, Cancun=0 (Cancun) (ethrex)
- [] Fork ID: Genesis=0, Cancun=0, BlocksBeforePeering=1 (Cancun) (ethrex)
- [] Fork ID: Genesis=0, Cancun=1 (Cancun) (ethrex)
- [] Fork ID: Genesis=0, Cancun=1, BlocksBeforePeering=1 (Cancun) (ethrex)
- [] Fork ID: Genesis=0, Cancun=1, Shanghai=1 (Cancun) (ethrex)
- [] Fork ID: Genesis=0, Cancun=1, Shanghai=1, BlocksBeforePeering=1 (Cancun) (ethrex)
- [] Fork ID: Genesis=0, Cancun=2 (Cancun) (ethrex)
- [] Fork ID: Genesis=1, Cancun=0, BlocksBeforePeering=1 (Cancun) (ethrex)
- [] Fork ID: Genesis=1, Cancun=1 (Cancun) (ethrex)
- [] Fork ID: Genesis=1, Cancun=2, BlocksBeforePeering=1 (Cancun) (ethrex)
- [] Fork ID: Genesis=1, Cancun=2, Shanghai=1 (Cancun) (ethrex)
- [] Fork ID: Genesis=1, Cancun=2, Shanghai=2, BlocksBeforePeering=1 (Cancun) (ethrex)
- [] Pre-Merge Fork Number > 0 (Cancun) (ethrex)
- [] Invalid PayloadAttributes, Missing BeaconRoot, Syncing=True (Cancun) (ethrex)
- [] Unique Payload ID, Modify Parent Beacon Root (Cancun) (ethrex)
- [] Unique Payload ID, Add Withdrawal (Cancun) (ethrex)
- [] Unique Payload ID, Modify Withdrawal Amount (Cancun) (ethrex)
- [] Unique Payload ID, Modify Withdrawal Index (Cancun) (ethrex)
- [] Unique Payload ID, Modify Withdrawal Validator (Cancun) (ethrex)
- [] Unique Payload ID, Modify Withdrawal Address (Cancun) (ethrex)
- [] Unique Payload ID, Remove Withdrawal (Cancun) (ethrex)
- [] Invalid NewPayload, ParentBeaconBlockRoot, Syncing=False, EmptyTxs=False, DynFeeTxs=False (Cancun) (ethrex)
- [] Invalid NewPayload, ParentBeaconBlockRoot, Syncing=True, EmptyTxs=False, DynFeeTxs=False (Cancun) (ethrex)
- [] Invalid NewPayload, BlobGasUsed, Syncing=False, EmptyTxs=False, DynFeeTxs=False (Cancun) (ethrex)
- [] Invalid NewPayload, BlobGasUsed, Syncing=True, EmptyTxs=False, DynFeeTxs=False (Cancun) (ethrex)
- [] Invalid NewPayload, Blob Count on BlobGasUsed, Syncing=False, EmptyTxs=False, DynFeeTxs=False (Cancun) (ethrex)
- [] Invalid NewPayload, Blob Count on BlobGasUsed, Syncing=True, EmptyTxs=False, DynFeeTxs=False (Cancun) (ethrex)
- [] Invalid NewPayload, ExcessBlobGas, Syncing=False, EmptyTxs=False, DynFeeTxs=False (Cancun) (ethrex)
- [] Invalid NewPayload, ExcessBlobGas, Syncing=True, EmptyTxs=False, DynFeeTxs=False (Cancun) (ethrex)
- [] Invalid NewPayload, VersionedHashes, Syncing=False, EmptyTxs=False, DynFeeTxs=False (Cancun) (ethrex)
- [] Invalid NewPayload, VersionedHashes, Syncing=True, EmptyTxs=False, DynFeeTxs=False (Cancun) (ethrex)
- [] Invalid NewPayload, VersionedHashes Version, Syncing=False, EmptyTxs=False, DynFeeTxs=False (Cancun) (ethrex)
- [] Invalid NewPayload, VersionedHashes Version, Syncing=True, EmptyTxs=False, DynFeeTxs=False (Cancun) (ethrex)
- [] Invalid NewPayload, Incomplete VersionedHashes, Syncing=False, EmptyTxs=False, DynFeeTxs=False (Cancun) (ethrex)
- [] Invalid NewPayload, Incomplete VersionedHashes, Syncing=True, EmptyTxs=False, DynFeeTxs=False (Cancun) (ethrex)
- [] Invalid NewPayload, Extra VersionedHashes, Syncing=False, EmptyTxs=False, DynFeeTxs=False (Cancun) (ethrex)
- [] Invalid NewPayload, Extra VersionedHashes, Syncing=True, EmptyTxs=False, DynFeeTxs=False (Cancun) (ethrex)
- [] Build Payload with Invalid ChainID Transaction, BlobTransactions (Cancun) (ethrex)
- [] Payload Build after New Invalid Payload: Invalid ParentBeaconBlockRoot (Cancun) (ethrex)
- [] Suggested Fee Recipient Test, BlobTransactions (Cancun) (ethrex)
- [] PrevRandao Opcode Transactions Test, BlobTransactions (Cancun) (ethrex)

**Comment by ElFantasma** [comment]
The script to obtain this list is not precise. 
awk returns the line of the _next_ test after a failing one.
Got my own list from the json resulting on the [Daily Hive Coverage run](https://github.com/lambdaclass/ethrex/actions/runs/12170666472):
```
cat run_result.json | jq '.testCases.[] | select(.summaryResult.pass == false) | .name'
```

```
Blob Transaction Ordering, Multiple Clients (Cancun) (ethrex)
ForkchoiceUpdatedV3 Set Head to Shanghai Payload, Null Payload Attributes (Cancun) (ethrex)
ForkchoiceUpdatedV3 To Request Shanghai Payload, Null Beacon Root (Cancun) (ethrex)
ForkchoiceUpdatedV3 To Request Shanghai Payload, Non-Null Beacon Root (Cancun) (ethrex)
ForkchoiceUpdatedV2 To Request Shanghai Payload, Non-Null Beacon Root (Cancun) (ethrex)
ForkchoiceUpdatedV2 To Request Cancun Payload, Non-Null Beacon Root (Cancun) (ethrex)
ForkchoiceUpdatedV2 To Request Cancun Payload, Missing Beacon Root (Cancun) (ethrex)
GetPayloadV3 To Request Shanghai Payload (Cancun) (ethrex)
GetPayloadV2 To Request Cancun Payload (Cancun) (ethrex)
NewPayloadV3 Before Cancun, Nil Data Fields, Nil Versioned Hashes, Nil Beacon Root (Cancun) (ethrex)
NewPayloadV3 Before Cancun, Nil ExcessBlobGas, 0x00 BlobGasUsed, Nil Versioned Hashes, Nil Beacon Root (Cancun) (ethrex)
NewPayloadV3 Before Cancun, 0x00 ExcessBlobGas, Nil BlobGasUsed, Nil Versioned Hashes, Nil Beacon Root (Cancun) (ethrex)
NewPayloadV3 Before Cancun, Nil Data Fields, Empty Array Versioned Hashes, Nil Beacon Root (Cancun) (ethrex)
NewPayloadV3 Before Cancun, Nil Data Fields, Nil Versioned Hashes, Zero Beacon Root (Cancun) (ethrex)
NewPayloadV3 Before Cancun, 0x00 Data Fields, Empty Array Versioned Hashes, Zero Beacon Root (Cancun) (ethrex)
ForkchoiceUpdatedV2 then ForkchoiceUpdatedV3 Valid Payload Building Requests (Cancun) (ethrex)
Request Blob Pooled Transactions Single (Cancun) (ethrex)
Request Blob Pooled Transactions Multiple (Cancun) (ethrex)
Invalid NewPayload, ReceiptsRoot, Syncing=False, EmptyTxs=False, DynFeeTxs=False (Cancun) (ethrex)
Invalid NewPayload, ReceiptsRoot, Syncing=True, EmptyTxs=False, DynFeeTxs=False (Cancun) (ethrex)
Invalid Missing Ancestor Syncing ReOrg, StateRoot, EmptyTxs=True, CanonicalReOrg=False, Invalid P9 (Cancun) (ethrex)
Invalid Missing Ancestor Syncing ReOrg, StateRoot, EmptyTxs=False, CanonicalReOrg=False, Invalid P9 (Cancun) (ethrex)
Invalid Missing Ancestor Syncing ReOrg, StateRoot, EmptyTxs=True, CanonicalReOrg=True, Invalid P9 (Cancun) (ethrex)
Invalid Missing Ancestor Syncing ReOrg, StateRoot, EmptyTxs=False, CanonicalReOrg=True, Invalid P9 (Cancun) (ethrex)
Invalid Missing Ancestor Syncing ReOrg, ReceiptsRoot, EmptyTxs=False, CanonicalReOrg=False, Invalid P8 (Cancun) (ethrex)
Invalid Missing Ancestor Syncing ReOrg, ReceiptsRoot, EmptyTxs=False, CanonicalReOrg=True, Invalid P8 (Cancun) (ethrex)
Invalid Missing Ancestor Syncing ReOrg, GasLimit, EmptyTxs=False, CanonicalReOrg=False, Invalid P8 (Cancun) (ethrex)
Invalid Missing Ancestor Syncing ReOrg, GasLimit, EmptyTxs=False, CanonicalReOrg=True, Invalid P8 (Cancun) (ethrex)
Invalid Missing Ancestor Syncing ReOrg, GasUsed, EmptyTxs=False, CanonicalReOrg=False, Invalid P8 (Cancun) (ethrex)
Invalid Missing Ancestor Syncing ReOrg, GasUsed, EmptyTxs=False, CanonicalReOrg=True, Invalid P8 (Cancun) (ethrex)
Invalid Missing Ancestor Syncing ReOrg, Timestamp, EmptyTxs=False, CanonicalReOrg=False, Invalid P8 (Cancun) (ethrex)
Invalid Missing Ancestor Syncing ReOrg, Timestamp, EmptyTxs=False, CanonicalReOrg=True, Invalid P8 (Cancun) (ethrex)
Invalid Missing Ancestor Syncing ReOrg, Incomplete Transactions, EmptyTxs=False, CanonicalReOrg=False, Invalid P9 (Cancun) (ethrex)
Invalid Missing Ancestor Syncing ReOrg, Incomplete Transactions, EmptyTxs=False, CanonicalReOrg=True, Invalid P9 (Cancun) (ethrex)
Invalid Missing Ancestor Syncing ReOrg, Transaction Signature, EmptyTxs=False, CanonicalReOrg=False, Invalid P9 (Cancun) (ethrex)
Invalid Missing Ancestor Syncing ReOrg, Transaction Signature, EmptyTxs=False, CanonicalReOrg=True, Invalid P9 (Cancun) (ethrex)
Invalid Missing Ancestor Syncing ReOrg, Transaction Nonce, EmptyTxs=False, CanonicalReOrg=False, Invalid P9 (Cancun) (ethrex)
Invalid Missing Ancestor Syncing ReOrg, Transaction Nonce, EmptyTxs=False, CanonicalReOrg=True, Invalid P9 (Cancun) (ethrex)
Invalid Missing Ancestor Syncing ReOrg, Transaction Gas, EmptyTxs=False, CanonicalReOrg=False, Invalid P9 (Cancun) (ethrex)
Invalid Missing Ancestor Syncing ReOrg, Transaction Gas, EmptyTxs=False, CanonicalReOrg=True, Invalid P9 (Cancun) (ethrex)
Invalid Missing Ancestor Syncing ReOrg, Transaction GasPrice, EmptyTxs=False, CanonicalReOrg=False, Invalid P9 (Cancun) (ethrex)
Invalid Missing Ancestor Syncing ReOrg, Transaction GasPrice, EmptyTxs=False, CanonicalReOrg=True, Invalid P9 (Cancun) (ethrex)
Invalid Missing Ancestor Syncing ReOrg, Transaction Value, EmptyTxs=False, CanonicalReOrg=False, Invalid P9 (Cancun) (ethrex)
Invalid Missing Ancestor Syncing ReOrg, Transaction Value, EmptyTxs=False, CanonicalReOrg=True, Invalid P9 (Cancun) (ethrex)
Sidechain Reorg (Cancun) (ethrex)
Transaction Re-Org, Re-Org Out (Cancun) (ethrex)
Transaction Re-Org, Re-Org to Different Block (Cancun) (ethrex)
Transaction Re-Org, New Payload on Revert Back (Cancun) (ethrex)
Re-Org Back into Canonical Chain, Depth=10, Execute Side Payload on Re-Org (Cancun) (ethrex)
Fork ID: Genesis=0, Cancun=2 (Cancun) (ethrex)
Fork ID: Genesis=0, Cancun=2, BlocksBeforePeering=1 (Cancun) (ethrex)
Fork ID: Genesis=0, Cancun=2, Shanghai=1 (Cancun) (ethrex)
Fork ID: Genesis=0, Cancun=2, Shanghai=1, BlocksBeforePeering=1 (Cancun) (ethrex)
Fork ID: Genesis=0, Cancun=2, Shanghai=2 (Cancun) (ethrex)
Fork ID: Genesis=0, Cancun=2, Shanghai=2, BlocksBeforePeering=1 (Cancun) (ethrex)
Fork ID: Genesis=1, Cancun=1 (Cancun) (ethrex)
Fork ID: Genesis=1, Cancun=1, BlocksBeforePeering=1 (Cancun) (ethrex)
Fork ID: Genesis=1, Cancun=1, Shanghai=1 (Cancun) (ethrex)
Fork ID: Genesis=1, Cancun=1, Shanghai=1, BlocksBeforePeering=1 (Cancun) (ethrex)
Fork ID: Genesis=1, Cancun=2, Shanghai=1 (Cancun) (ethrex)
Fork ID: Genesis=1, Cancun=2, Shanghai=1, BlocksBeforePeering=1 (Cancun) (ethrex)
Pre-Merge Fork Number > 0 (Cancun) (ethrex) 
```
