### ISSUE TITLE
[Tracking] Hive `engine-withdrawals` test suite (Shanghai)

### ISSUE THREAD

**Issue by fkrause98** [lambdaclass/ethrex#1586]
```shell
make run-hive SIMULATION=ethereum/engine TEST_PATTERN="engine-withdrawals"
cat $(ls -t hive/workspace/logs/*-*.json | head -n1) | jq '.testCases[] | select(.summaryResult.pass == false) | .name'
```

Currently failing tests:
- [x] #1605
- [x] #1608
- [x] Sync after 2 blocks - Withdrawals on Block 1 - Single Withdrawal Account - No Transactions
- [x] Sync after 2 blocks - Withdrawals on Block 1 - Single Withdrawal Account
- [x] Sync after 2 blocks - Withdrawals on Block 2 - Multiple Withdrawal Accounts - No Transactions
- [x] Sync after 2 blocks - Withdrawals on Block 2 - Multiple Withdrawal Accounts
- [ ] Sync after 128 blocks - Withdrawals on Block 2 - Multiple Withdrawal Accounts 
- [x] Withdrawals Fork on Block 1 - 1 Block Re-Org
- [x] Withdrawals Fork On Genesis
- [x] Withdrawals Fork on Block 1 - 8 Block Re-Org NewPayload
- [ ] Withdrawals Fork on Block 1 - 8 Block Re-Org, Sync
- [x] Withdrawals Fork on Block 8 - 10 Block Re-Org NewPayload
- [ ] Withdrawals Fork on Block 8 - 10 Block Re-Org Sync
- [x] Withdrawals Fork on Canonical Block 8 / Side Block 7 - 10 Block Re-Org
- [ ] Withdrawals Fork on Canonical Block 8 / Side Block 7 - 10 Block Re-Org Sync
- [x] Withdrawals Fork on Canonical Block 8 / Side Block 9 - 10 Block Re-Org
- [ ] Withdrawals Fork on Canonical Block 8 / Side Block 9 - 10 Block Re-Org Sync
- [x] GetPayloadBodiesByRange
- [x] Withdrawals Fork on Block 1
- [x] GetPayloadBodies After Sync
- [x] GetPayloadBodiesByRange (Sidechain)
- [x] GetPayloadBodiesByRange (Empty Transactions/Withdrawals)
- [x] GetPayloadBodiesByHash
- [x] GetPayloadBodiesByHash (Empty Transactions/Withdrawals)
- [x] GetPayloadBodies Parallel
- [x] Withdrawals Fork on Block 2
- [x] Withdrawals Fork on Block 3
- [x] Withdraw to a single account
- [x] Withdraw to two accounts
- [x] Withdraw many accounts
- [x] Withdraw zero amount

**Comment by mpaulucci** [comment]
Moved to https://github.com/lambdaclass/ethrex/issues/1285
