### ISSUE TITLE
[Tracking] JSON-RPC API

### ISSUE THREAD

**Issue by MegaRedHand** [lambdaclass/ethrex#172]
## engine

- [ ] #49
- [x] #51
- [x] Implement engine_newPayloadV3 (block building) RPC endpoint
- [x] #50
- [ ] #1548
- [ ] #1549

## eth

- [X] Implement eth_getBlockByHash RPC endpoint (#31)
- [X] Implement eth_getBlockByNumber RPC endpoint (#31)
- [x] #34
- [x] #32
- [X] #33
- [X] Implement eth_getTransactionByBlockHashAndIndex RPC endpoint (#35)
- [X] Implement eth_getTransactionByBlockNumberAndIndex RPC endpoint (#35)
- [X] #36
- [X] #38
- [x] #39
- [x] #173
- [ ] #174
- [x] #175
- [x] #176
- [x] #177
- [x] #178
- [ ] #179
- [x] #209
