### ISSUE TITLE
LEVM: [Tracking] Ethereum Foundation tests

### ISSUE THREAD

**Issue by iinaki** [lambdaclass/ethrex#741]
- [ ] https://github.com/lambdaclass/ethereum_rust/issues/603
- [ ] https://github.com/lambdaclass/ethereum_rust/issues/736
- [x] https://github.com/lambdaclass/ethereum_rust/issues/737
- [ ] https://github.com/lambdaclass/ethereum_rust/issues/742
- [ ] https://github.com/lambdaclass/ethereum_rust/issues/743
- [ ] https://github.com/lambdaclass/ethereum_rust/issues/744
- [x] #745
- [ ] https://github.com/lambdaclass/ethereum_rust/issues/746
- [ ] https://github.com/lambdaclass/ethereum_rust/issues/747
- [ ] https://github.com/lambdaclass/ethereum_rust/issues/748
- [ ] https://github.com/lambdaclass/ethereum_rust/issues/749
- [ ] https://github.com/lambdaclass/ethereum_rust/issues/750
- [ ] https://github.com/lambdaclass/ethereum_rust/issues/751
- [ ] https://github.com/lambdaclass/ethereum_rust/issues/752
- [ ] https://github.com/lambdaclass/ethereum_rust/issues/753
- [ ] https://github.com/lambdaclass/ethereum_rust/issues/754
- [ ] https://github.com/lambdaclass/ethereum_rust/issues/755
- [ ] https://github.com/lambdaclass/ethereum_rust/issues/756
- [ ] https://github.com/lambdaclass/ethereum_rust/issues/757
- [ ] https://github.com/lambdaclass/ethereum_rust/issues/758
- [ ] https://github.com/lambdaclass/ethereum_rust/issues/759
- [ ] https://github.com/lambdaclass/ethereum_rust/issues/760
- [ ] https://github.com/lambdaclass/ethereum_rust/issues/761
- [ ] https://github.com/lambdaclass/ethereum_rust/issues/762
- [ ] https://github.com/lambdaclass/ethereum_rust/issues/763
- [ ] https://github.com/lambdaclass/ethereum_rust/issues/764
- [ ] https://github.com/lambdaclass/ethereum_rust/issues/765
- [ ] https://github.com/lambdaclass/ethereum_rust/issues/766
- [ ] https://github.com/lambdaclass/ethereum_rust/issues/767
- [ ] https://github.com/lambdaclass/ethereum_rust/issues/768
- [ ] https://github.com/lambdaclass/ethereum_rust/issues/769
- [ ] https://github.com/lambdaclass/ethereum_rust/issues/770
- [ ] https://github.com/lambdaclass/ethereum_rust/issues/771
- [ ] https://github.com/lambdaclass/ethereum_rust/issues/772
- [ ] https://github.com/lambdaclass/ethereum_rust/issues/773
- [ ] https://github.com/lambdaclass/ethereum_rust/issues/774
- [ ] https://github.com/lambdaclass/ethereum_rust/issues/775
- [ ] https://github.com/lambdaclass/ethereum_rust/issues/776
- [ ] https://github.com/lambdaclass/ethereum_rust/issues/777
- [ ] https://github.com/lambdaclass/ethereum_rust/issues/778
- [ ] https://github.com/lambdaclass/ethereum_rust/issues/779
- [ ] https://github.com/lambdaclass/ethereum_rust/issues/780
- [ ] https://github.com/lambdaclass/ethereum_rust/issues/781
- [ ] https://github.com/lambdaclass/ethereum_rust/issues/782
- [ ] https://github.com/lambdaclass/ethereum_rust/issues/783
- [ ] https://github.com/lambdaclass/ethereum_rust/issues/784
- [ ] https://github.com/lambdaclass/ethereum_rust/issues/785
- [ ] https://github.com/lambdaclass/ethereum_rust/issues/786

Current not ignored groups:
- [x] stShift
41 tests
- [x] eip7516_blobgasfee
3 tests
- [x] Pyspecs/frontier/opcodes
2 tests
- [x] eip2930_access_list
1 test
- [x] eip1344_chainid
1 test
- [x] stChainId
2 tests
- [x] vmBitwiseLogicOperation
11 tests
- [x] stCallDelegateCodesCallCodeHomestead
58 tests
- [x] stSLoadTest
1 test

**Total: 120/2807 tests passing**
